### ISSUE TITLE
Interested in contributing iOS port / build instructions

### ISSUE THREAD

**Issue by chrisballinger** [SilentCircle/libsalamander#4]
Hey, great work on libsalamander!

I may be interested in contributing an iOS port. I haven't studied all of the source in detail, but from a quick glance it seems like the code is pretty much platform independent C++. Is there anything I should be aware of before I dive in?

Also it appears there are a few files with LGPLv3 license headers, are those meant to be available under the project's Apache 2.0 license?

Thanks!

**Comment by traviscross** [comment]
Hi Chris; it should build straightforwardly for iOS.  We do build it ourselves that way for Silent Phone iOS.  @wernerd might have more comments here.

The LGPLv3 licensed files are copied from ZRTPCPP.  They are licensed as intended at the moment.

**Comment by wernerd** [comment]
Building for Linux works out-of-the-box. Prerequisites are that you have a local git repo of ZRTPCPP because the Salamander lib uses encryption and hash modules/implementations from it. You also need Google's protobuf library, the CmakeLists.txt checks for protobuf-lite>=2.6.1.

The just do the usual cmake limbo:

mkdir build
cd build
cmake -DUNITTESTS=true ..
make

The  -DUNITTESTS builds a shared object lib that contains all necessary modules (some from ZRTPCPP), it also builds the unit test modules

The parameter -DSTANDALONE=true also builds a shared object lib that contains all necessary modules, however not the unit tests and also not the code in the lib which only the unit test modules use.

For iOS you need to setup the Xcode project AFAIK - I'm not an iOS specialist, however the code works with iOS and was tested.
